#!/bin/bash
# burrito client

connect_db () {
    if [[ -z "${MARIADB_SERVICE_HOST}" ]]; then
        echo "Error) No MARIADB_SERVICE_HOST exists."
    else
        mariadb -h mariadb -u root -p --ssl \
            --ssl-ca=/etc/mysql/certs/ca.crt \
            --ssl-cert=/etc/mysql/certs/tls.crt \
            --ssl-key=/etc/mysql/certs/tls.key \
            --ssl-verify-server-cert=true
    fi
}
execute_burrito () {
    openstack "$@"
}
post_install_burrito () {
    echo -n "Creating host aggregate..."
    if ! openstack aggregate show public-zone &> /dev/null
    then
        openstack aggregate create public-zone
    fi
    openstack aggregate set --zone public-zone public-zone
    echo "Done"
    echo -n "Set volume type to private..."
    for vol_type in $(openstack volume type list -c ID -f value);do
        cinder type-update --is-public False ${vol_type} &> /dev/null
    done
    echo "Done"
}
run_burrito () {
    # run post_install_burrito
    post_install_burrito

    # check if client can reach each openstack service.
    declare -A clients
    clients=(
        ["cinder"]="300"
        ["glance"]="300"
        ["keystone"]="300"
        ["neutron"]="200"
        ["nova"]="200"
    )
    
    while true; do
        for c in ${!clients[@]}; do
            code=$(curl --silent --insecure --output /dev/null --include \
                    --max-time 3 --write-out "%{http_code}" \
                    https://$c.openstack.svc.cluster.local:8443/)
            if [ x"$code" != x"${clients[$c]}" ]; then
                echo "$c service has a problem."
            fi
            sleep 1
        done
        sleep 30
    done
}
test_burrito () {
    PARAM=${1:-"--provider"}
    /usr/local/bin/burrito-test.sh ${PARAM}
}
version_burrito () {
    openstack module list
}
USAGE () {
    echo "USAGE: $0 {-h|-d|-e|-r|-t|-v}" 1>&2
    echo ""
    echo " -h --help            Display this help message."
    echo " -d --database        Connect to openstack database."
    echo " -e --execute         Execute burrito command."
    echo " -r --run             Run burrito client."
    echo " -t --test            Run burrito-test.sh script."
    echo " -v --version         Show openstack client versions."
}
if [ $# -lt 1 ]; then
    USAGE
    exit 0
fi

OPT=$1
shift
# Get argument
while true
do
    case "$OPT" in
        -d | --database)
            connect_db
            break
            ;;
        -e | --execute)
            execute_burrito "$@"
            break
            ;;
        -h | --help)
            USAGE
            break
            ;;
        -p | --post-install)
            post_install_burrito
            break
            ;;
        -r | --run)
            run_burrito
            break
            ;;
        -t | --test)
            test_burrito
            break
            ;;
        -v | --version)
            version_burrito
            break
            ;;
        *)
            echo Error: unknown option: "$OPT" 1>&2
            echo " "
            USAGE
            break
            ;;
    esac
done
