apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: btx
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      application: btx
  serviceName: btx
  replicas: 1
  template:
    metadata:
      labels:
        application: btx
    spec:
      dnsPolicy: ClusterFirst
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: btx
      initContainers:
        - name: init
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: false
            runAsUser: 0
          command:
            - "/bin/bash"
            - "-c"
            - "chown 1000:100 /data"
          volumeMounts:
            - mountPath: /data
              name: btx-pvc
              readOnly: false
      containers:
        - name: btx
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "openstack-cookie"
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
          envFrom:
            - configMapRef:
                name: btx
          volumeMounts:
            - mountPath: /etc/mysql/certs/tls.crt
              name: mariadb-tls-direct
              readOnly: true
              subPath: tls.crt
            - mountPath: /etc/mysql/certs/tls.key
              name: mariadb-tls-direct
              readOnly: true
              subPath: tls.key
            - mountPath: /etc/mysql/certs/ca.crt
              name: mariadb-tls-direct
              readOnly: true
              subPath: ca.crt
            - mountPath: /tmp
              name: tmp-volume
              readOnly: false
            - mountPath: /data
              name: btx-pvc
              readOnly: false
            - mountPath: /root
              name: s3cfg
              readOnly: true
            - mountPath: /etc/ceph/ceph.client.admin.keyring
              name: ceph-admin-keyring
              readOnly: true
            - mountPath: /etc/ceph/ceph.conf
              name: cephconf
              readOnly: true
            - mountPath: /etc/localtime
              name: etclocaltime
              readOnly: true
          resources:
              {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: mariadb-tls-direct
          secret:
            defaultMode: 292
            secretName: mariadb-tls-direct
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 100Mi
        - name: s3cfg
          secret:
            secretName: s3cfg
            defaultMode: 0400
            items:
              - key: s3cfg
                path: .s3cfg
        - name: ceph-admin-keyring
          hostPath:
            path: /etc/ceph/ceph.client.admin.keyring
            type: File
        - name: cephconf
          hostPath:
            path: /etc/ceph/ceph.conf
            type: File
        - name: etclocaltime
          hostPath:
            path: /etc/localtime
            type: File
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: btx-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.btx.pvc.size }}
...
